const headers = [
    [
        { label: 'Metrics', colspan: 2 },
        { label: 'Total', colspan: 6 },
        { label: 'Women', colspan: 7 },
        { label: 'Men', colspan: 7 },
    ],
    // [
    //     'Name',
    //     'Season',
    //     'STD Pre Mkd',
    //     'Incr %',
    //     'STD Post Mkd',
    //     'Incr %',
    //     'Full Season',
    //     'Incr %',
    //     'STD Pre Mkd',
    //     'Incr %',
    //     'STD Post Mkd',
    //     'Incr %',
    //     'Full Season',
    //     'Incr %',
    //     'Cont %',
    //     'STD Pre Mkd',
    //     'Incr %',
    //     'STD Post Mkd',
    //     'Incr %',
    //     'Full Season',
    //     'Incr %',
    //     'Cont %',
    // ],
    [
        'Name',
        'Season',
        'C-STD Pre Mkd',
        'D-Incr %',
        'E-STD Post Mkd',
        'F-Incr %',
        'G-Full Season',
        'H-Incr %',
        'I-STD Pre Mkd',
        'J-Incr %',
        'K-STD Post Mkd',
        'L-Incr %',
        'M-Full Season',
        'N-Incr %',
        'O-Cont %',
        'P-STD Pre Mkd',
        'Q-Incr %',
        'R-STD Post Mkd',
        'S-Incr %',
        'T-Full Season',
        'U-Incr %',
        'V-Cont %',
    ],
];

export default headers;
