const datagrid = {
    info: {
        total: 17,
        metrics: 3,
        start_row: 0,
        row_span: 5,
        total_cols: 22,
        has_gaps: true,
    },
    data: [
        {
            metric: 'Sales',
            seasonyear: 'SS18',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            dec: '',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            future: '',
        },
        {
            metric: 'Sales',
            seasonyear: 'SS17',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            dec: '',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            future: '',
        },
        {
            metric: 'Sales',
            seasonyear: 'SS16',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            dec: '',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            future: '',
        },
        {
            metric: 'Sales',
            seasonyear: 'SS15',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            dec: '',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            future: '',
        },
        {
            metric: 'Sales',
            seasonyear: 'SS14',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            dec: '',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            future: '',
        },
        {
            empty: '',
        },
        {
            metric: 'COGS',
            seasonyear: 'SS18',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            dec: '',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            future: '',
        },
        {
            metric: 'COGS',
            seasonyear: 'SS17',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            dec: '',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            future: '',
        },
        {
            metric: 'COGS',
            seasonyear: 'SS16',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            dec: '',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            future: '',
        },
        {
            metric: 'COGS',
            seasonyear: 'SS15',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            dec: '',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            future: '',
        },
        {
            metric: 'COGS',
            seasonyear: 'SS14',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            dec: '',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            future: '',
        },
        {
            empty: '',
        },
        {
            metric: 'GM $',
            seasonyear: 'SS18',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            dec: '',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            future: '',
        },
        {
            metric: 'GM $',
            seasonyear: 'SS17',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            dec: '',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            future: '',
        },
        {
            metric: 'GM $',
            seasonyear: 'SS16',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            dec: '',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            future: '',
        },
        {
            metric: 'GM $',
            seasonyear: 'SS15',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            dec: '',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            future: '',
        },
        {
            metric: 'GM $',
            seasonyear: 'SS14',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            dec: '',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            jun: '',
            jul: '',
            future: '',
        },
    ],
};


export default datagrid;