const datagrid = {
    info: {
        total: 17,
        metrics: 3,
        start_row: 0,
        row_span: 5,
        total_cols: 25,
        has_gaps: false,
    },
    data: [
        {
            metric: 'Sales',
            seasonyear: 'SS18',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb1: '',
            mar1: '',
            apr1: '',
            may1: '',
            jun1: '',
            jul1: '',
            aug1: '',
            sep1: '',
            oct1: '',
            nov1: '',
            dec1: '',
            jan2: '',
            feb2: '',
            mar2: '',
            apr2: '',
            may2: '',
            jun2: '',
            jul2: '',
            future: '',
        },
        {
            metric: 'Sales',
            seasonyear: 'SS17',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb1: '',
            mar1: '',
            apr1: '',
            may1: '',
            jun1: '',
            jul1: '',
            aug1: '',
            sep1: '',
            oct1: '',
            nov1: '',
            dec1: '',
            jan2: '',
            feb2: '',
            mar2: '',
            apr2: '',
            may2: '',
            jun2: '',
            jul2: '',
            future: '',
        },
        {
            metric: 'Sales',
            seasonyear: 'SS16',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb1: '',
            mar1: '',
            apr1: '',
            may1: '',
            jun1: '',
            jul1: '',
            aug1: '',
            sep1: '',
            oct1: '',
            nov1: '',
            dec1: '',
            jan2: '',
            feb2: '',
            mar2: '',
            apr2: '',
            may2: '',
            jun2: '',
            jul2: '',
            future: '',
        },
        {
            metric: 'Sales',
            seasonyear: 'SS15',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb1: '',
            mar1: '',
            apr1: '',
            may1: '',
            jun1: '',
            jul1: '',
            aug1: '',
            sep1: '',
            oct1: '',
            nov1: '',
            dec1: '',
            jan2: '',
            feb2: '',
            mar2: '',
            apr2: '',
            may2: '',
            jun2: '',
            jul2: '',
            future: '',
        },
        {
            metric: 'Sales',
            seasonyear: 'SS14',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb1: '',
            mar1: '',
            apr1: '',
            may1: '',
            jun1: '',
            jul1: '',
            aug1: '',
            sep1: '',
            oct1: '',
            nov1: '',
            dec1: '',
            jan2: '',
            feb2: '',
            mar2: '',
            apr2: '',
            may2: '',
            jun2: '',
            jul2: '',
            future: '',
        },
        {
            empty: '',
        },
        {
            metric: 'COGS',
            seasonyear: 'SS18',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb1: '',
            mar1: '',
            apr1: '',
            may1: '',
            jun1: '',
            jul1: '',
            aug1: '',
            sep1: '',
            oct1: '',
            nov1: '',
            dec1: '',
            jan2: '',
            feb2: '',
            mar2: '',
            apr2: '',
            may2: '',
            jun2: '',
            jul2: '',
            future: '',
        },
        {
            metric: 'COGS',
            seasonyear: 'SS17',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb1: '',
            mar1: '',
            apr1: '',
            may1: '',
            jun1: '',
            jul1: '',
            aug1: '',
            sep1: '',
            oct1: '',
            nov1: '',
            dec1: '',
            jan2: '',
            feb2: '',
            mar2: '',
            apr2: '',
            may2: '',
            jun2: '',
            jul2: '',
            future: '',
        },
        {
            metric: 'COGS',
            seasonyear: 'SS16',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb1: '',
            mar1: '',
            apr1: '',
            may1: '',
            jun1: '',
            jul1: '',
            aug1: '',
            sep1: '',
            oct1: '',
            nov1: '',
            dec1: '',
            jan2: '',
            feb2: '',
            mar2: '',
            apr2: '',
            may2: '',
            jun2: '',
            jul2: '',
            future: '',
        },
        {
            metric: 'COGS',
            seasonyear: 'SS15',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb1: '',
            mar1: '',
            apr1: '',
            may1: '',
            jun1: '',
            jul1: '',
            aug1: '',
            sep1: '',
            oct1: '',
            nov1: '',
            dec1: '',
            jan2: '',
            feb2: '',
            mar2: '',
            apr2: '',
            may2: '',
            jun2: '',
            jul2: '',
            future: '',
        },
        {
            metric: 'COGS',
            seasonyear: 'SS14',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb1: '',
            mar1: '',
            apr1: '',
            may1: '',
            jun1: '',
            jul1: '',
            aug1: '',
            sep1: '',
            oct1: '',
            nov1: '',
            dec1: '',
            jan2: '',
            feb2: '',
            mar2: '',
            apr2: '',
            may2: '',
            jun2: '',
            jul2: '',
            future: '',
        },
        {
            empty: '',
        },
        {
            metric: 'GM $',
            seasonyear: 'SS18',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb1: '',
            mar1: '',
            apr1: '',
            may1: '',
            jun1: '',
            jul1: '',
            aug1: '',
            sep1: '',
            oct1: '',
            nov1: '',
            dec1: '',
            jan2: '',
            feb2: '',
            mar2: '',
            apr2: '',
            may2: '',
            jun2: '',
            jul2: '',
            future: '',
        },
        {
            metric: 'GM $',
            seasonyear: 'SS17',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb1: '',
            mar1: '',
            apr1: '',
            may1: '',
            jun1: '',
            jul1: '',
            aug1: '',
            sep1: '',
            oct1: '',
            nov1: '',
            dec1: '',
            jan2: '',
            feb2: '',
            mar2: '',
            apr2: '',
            may2: '',
            jun2: '',
            jul2: '',
            future: '',
        },
        {
            metric: 'GM $',
            seasonyear: 'SS16',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb1: '',
            mar1: '',
            apr1: '',
            may1: '',
            jun1: '',
            jul1: '',
            aug1: '',
            sep1: '',
            oct1: '',
            nov1: '',
            dec1: '',
            jan2: '',
            feb2: '',
            mar2: '',
            apr2: '',
            may2: '',
            jun2: '',
            jul2: '',
            future: '',
        },
        {
            metric: 'GM $',
            seasonyear: 'SS15',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb1: '',
            mar1: '',
            apr1: '',
            may1: '',
            jun1: '',
            jul1: '',
            aug1: '',
            sep1: '',
            oct1: '',
            nov1: '',
            dec1: '',
            jan2: '',
            feb2: '',
            mar2: '',
            apr2: '',
            may2: '',
            jun2: '',
            jul2: '',
            future: '',
        },
        {
            metric: 'GM $',
            seasonyear: 'SS14',
            total_std: '',
            total_incr_std: '',
            full_season: '',
            full_season_incr: '',
            feb1: '',
            mar1: '',
            apr1: '',
            may1: '',
            jun1: '',
            jul1: '',
            aug1: '',
            sep1: '',
            oct1: '',
            nov1: '',
            dec1: '',
            jan2: '',
            feb2: '',
            mar2: '',
            apr2: '',
            may2: '',
            jun2: '',
            jul2: '',
            future: '',
        },
    ],
};

export default datagrid;
