export const dataT = [
    {
        metric: 'SALES',
        seasonyear: 'SS20 Act',
        total_stdpremarkdown: '62345',
        total_incr_stdpremarkdown: '6235',
        total_stdpostmarkdown: '2344',
        total_incr_stdpostmarkdown: '2356623',
        total_full: '1854',
        total_full_incr: '3746 ',
        women_stdpremarkdown: 0,
        women_incr_stdpremarkdown: '73475',
        women_stdpostmarkdown: 0,
        women_incr_stdpostmarkdown: '124',
        women_full: 0,
        women_full_incr: '73473',
        women_full_cont: '73567',
        men_stdpremarkdown: 0,
        men_incr_stdpremarkdown: '9784',
        men_stdpostmarkdown: 0,
        men_incr_stdpostmarkdown: '12443',
        men_full: 0,
        men_full_incr: '523623',
        men_full_cont: '63456',
    },
];
