const REQUEST_BUDGETS = 'REQUEST_BUDGETS';
const RECEIVE_BUDGETS = 'RECEIVE_BUDGETS';
const REQUEST_SEASONS = 'REQUEST_SEASONS';
const RECEIVE_SEASONS = 'RECEIVE_SEASONS';
const REQUEST_CREATE_BUDGET = 'REQUEST_CREATE_BUDGET';
const RECEIVE_CREATE_BUDGET = 'RECEIVE_CREATE_BUDGET';

export default {
    REQUEST_BUDGETS,
    RECEIVE_BUDGETS,
    REQUEST_SEASONS,
    RECEIVE_SEASONS,
    REQUEST_CREATE_BUDGET,
    RECEIVE_CREATE_BUDGET,
};
