const REQUEST_BUDGETS = 'REQUEST_BUDGETS';
const RECEIVE_BUDGETS = 'RECEIVE_BUDGETS';
const FAILED_BUDGETS = 'FAILED_BUDGETS';

const REQUEST_SEASONS = 'REQUEST_SEASONS';
const RECEIVE_SEASONS = 'RECEIVE_SEASONS';
const FAILED_SEASONS = 'FAILED_SEASONS';

const REQUEST_CREATE_BUDGET = 'REQUEST_CREATE_BUDGET';
const RECEIVE_CREATE_BUDGET = 'RECEIVE_CREATE_BUDGET';
const FAILED_CREATE_BUDGET = 'FAILED_CREATE_BUDGET';

export default {
    REQUEST_BUDGETS,
    RECEIVE_BUDGETS,
    FAILED_BUDGETS,

    REQUEST_SEASONS,
    RECEIVE_SEASONS,
    FAILED_SEASONS,

    REQUEST_CREATE_BUDGET,
    RECEIVE_CREATE_BUDGET,
    FAILED_CREATE_BUDGET,
};
