const headers = [
    [
        'A-Name',
        'B-Season/Year',
        'C-STD Pre-Markdown',
        'D-Incr%',
        'E-STD Post-Markdown',
        'F-Incr%',
        'G-Full Season',
        'H-Incr%',
        'I-Feb',
        'J-Mar',
        'K-Apr',
        'L-May',
        'M-Jun',
        'N-Jul',
        'O-Aug',
        'P-Sep',
        'Q-Oct',
        'R-Nov',
        'S-Dec',
        'T-Jan',
        'U-Feb',
        'V-Mar',
        'W-Apr',
        'X-May',
        'Y-Jun',
        'Z-Jul',
        'AB-Future',
    ],
];

export default headers;
