const REQUEST_BUDGETS_CONFIG_DATA = 'REQUEST_BUDGETS_CONFIG_DATA';
const RECEIVE_BUDGETS_CONFIG_DATA = 'RECEIVE_BUDGETS_CONFIG_DATA';
const REQUEST_BUDGETS_DATA = 'REQUEST_BUDGETS_DATA';
const RECEIVE_BUDGETS_DATA = 'RECEIVE_BUDGETS_DATA';
const REQUEST_SPREAD_DATA = 'REQUEST_SPREAD_DATA';
const RECEIVE_SPREAD_DATA = 'RECEIVE_SPREAD_DATA';
const SET_FILTER_SETUP = 'SET_FILTER_SETUP';
const RESET_BUDGETS_DATA = 'RESET_BUDGETS_DATA';
const REQUEST_VIEW_DOWNLOAD = 'REQUEST_VIEW_DOWNLOAD';

export default {
    REQUEST_BUDGETS_CONFIG_DATA,
    RECEIVE_BUDGETS_CONFIG_DATA,
    REQUEST_BUDGETS_DATA,
    RECEIVE_BUDGETS_DATA,
    REQUEST_SPREAD_DATA,
    RECEIVE_SPREAD_DATA,
    SET_FILTER_SETUP,
    RESET_BUDGETS_DATA,
    REQUEST_VIEW_DOWNLOAD,
};
