const headers = [
    [
        'A-Name',
        'B-Season/Year',
        'C-STD Pre-Markdown',
        'D-Incr%',
        'E-STD Post-Markdown',
        'F-Incr%',
        'G-Full Season',
        'H-Incr%',
        'I-Previous',
        'J-Feb',
        'K-Mar',
        'L-Apr',
        'M-May',
        'N-Jun',
        'O-Jul',
        'P-Aug',
        'Q-Sep',
        'R-Oct',
        'S-Nov',
        'T-Dec',
        'U-Jan',
        'V-Feb',
        'W-Mar',
        'X-Apr',
        'Y-May',
        'Z-Jun',
        'AA-Jul',
        'AB-Future',
    ],
];

export default headers;
